[project]
name = "mzkit"
version = "0.1.0"
description = "Toolkit for inspecting LC/MS data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy<=2.2",
    "pyopenms>=3.4.0",
    "pyqt5==5.15",
    "pyqt5-stubs==5.15.6",
    "pyqtgraph<=0.13.7",
    "scipy<=1.15.1",
]
