from PyQt5 import QtCore, QtGui
import pyqtgraph as pg


from typing import Optional, Literal, TYPE_CHECKING

if TYPE_CHECKING:
    from gui.views.sample_viewer.sample_widget_manager import SampleWidgetManager
    from gui.widgets.SampleWidget import SampleWidget
    from gui.views.sample_viewer.model import SampleViewerItemModel
    from core.data_structs import (
        SampleUUID,
        FeaturePointer,
        ScanArray,
    )

class EnsembleUIManager(QtCore.QObject):
    """
    Manages UI elements pertaining to Ensembles
    """
    def __init__(
        self,
        model: Optional['SampleViewerItemModel'],
        widget_manager: 'SampleWidgetManager',
    ):
        super().__init__()
        self._model = model
        self._widget_mgr = widget_manager

    def set_model(
        self,
        model: 'SampleViewerItemModel',
    ):
        self._model = model

    def display_ensembles_for_all_samples(
        self,
        ms_level: Literal[1, 2] = 1,
    ):
        """
        Adds ensemble overlays to all visible widgets
        """
        for uuid, widget in self._widget_mgr.get_all_widgets().items():
            self.clear_ensembles_for_sample(
                uuid=uuid,
            )

            self.display_ensembles_for_sample(
                uuid=uuid,
                ms_level=ms_level,
            )

    def display_ensembles_for_sample(
        self,
        uuid: 'SampleUUID',
        ms_level: Literal[1, 2] = 1,
    ):
        """
        Renders all ensembles for a given sample as colored peak overlays

        :param uuid: Sample UUID
        :param ms_level: MS level to display (1 or 2, default 1)
        """
        injection = self._model.getInjection(uuid)
        if not injection:
            return

        widget = self._widget_mgr.get_widget(uuid)
        if not widget:
            return

        # Clear existing peaks first to prevent stale state
        widget.clearPeaks()

        # Iterate through injection's ensembles and add peak overlays
        for idx, (ensemble_uuid, ensemble) in enumerate(
            injection.ensembles.items()
        ):
            # Get base cofeature chrom.
            chrom_arr = ensemble.get_base_chromatogram(ms_level)

            widget.addPeak(
                chrom=chrom_arr,
                uuid=ensemble_uuid,
                color=_generate_ensemble_color(ensemble_uuid)
            )

    def clear_ensembles_for_sample(
        self,
        uuid: 'SampleUUID',
    ):
        """
        Remove all ensemble overlays for given sample
        """
        widget = self._widget_mgr.get_widget(uuid)
        if widget:
            widget.clearPeaks()

    def show_scan_window_selector(
        self,
        uuid: 'SampleUUID',
        ms_level: Literal[1, 2],
        mass_lane_idx: int,
        initial_scan_window: int,
    ):
        """
        Shows a 'scan window selector' that can be
        used to define the duration with which a user
        would like to extract an Ensemble

        :param uuid: Sample UUID
        :param ms_level:
        :param mass_lane_idx:
        :param initial_scan_window:
        """
        # Clear previous scan window selector
        self.clear_scan_window_selector()

        # Retrieve a feature pointer corresponding to an XIC of entire lane
        scan_array: 'ScanArray' = self._model.getInjection(
            uuid
        ).get_scan_array(
            ms_level=ms_level
        )

        ftr_ptr: 'FeaturePointer'= scan_array. make_feature_pointer(
            mass_lane_idx=mass_lane_idx,
            scan_idxs=None, # returns whole lane
        )

        # Get default rt edges to palce the window initially
        apex_idx: int = ftr_ptr.get_max_intsy_scan_num(scan_array)
        rt_start = scan_array.rt_arr[apex_idx - initial_scan_window]
        rt_end = scan_array.rt_arr[apex_idx + initial_scan_window]

        # Finally, add the graphic to the appropriate sample_widget
        sample_widget: 'SampleWidget' = self._widget_mgr.get_widget(uuid)
        sample_widget.addWindowSelector(
            bounds=(rt_start, rt_end),
            display_arr=ftr_ptr.get_chrom_array(scan_array),
        )

    def clear_scan_window_selector(self):
        """
        Removes all the graphics generated by .show_scan_window_selector()
        """
        for uuid, sample_widget in self._widget_mgr.get_all_widgets().items():
            sample_widget.clearWindowSelector()

    def get_selected_scan_window(
        self,
        uuid: 'SampleUUID'
    ) -> tuple[float, float]:
        """
        Returns a tuple (start, end) defining whatever region is currently
        highlighted by the scan window selector.

        If no scan window selector is present, returns (0, 0)
        """
        sample_widget = self._widget_mgr.get_widget(uuid)
        return sample_widget.getWindowSelectorBounds()


def _generate_ensemble_color(
    idx: int,
) -> QtGui.QColor:
    """
    Avoids generating grey, which is used for raw data
    """
    return pg.intColor(
        idx,
        hues=12,
        minValue=150,
        maxValue=255,
        sat=128,
    )

