# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalyteTableViewerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushShowInSamples = QtWidgets.QPushButton(Form)
        self.pushShowInSamples.setObjectName("pushShowInSamples")
        self.horizontalLayout.addWidget(self.pushShowInSamples)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.viewTableAnalytes = QtWidgets.QTableView(Form)
        self.viewTableAnalytes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.viewTableAnalytes.setObjectName("viewTableAnalytes")
        self.verticalLayout.addWidget(self.viewTableAnalytes)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushShowInSamples.setText(_translate("Form", "Inspect selected analytes in sample viewer"))
