# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChromWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setMinimumSize(QtCore.QSize(0, 200))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chromPlotWidget = ChromPlotWidget(Form)
        self.chromPlotWidget.setObjectName("chromPlotWidget")
        self.horizontalLayout_2.addWidget(self.chromPlotWidget)
        self.fprintPlotWidget = FPrintWidget(Form)
        self.fprintPlotWidget.setObjectName("fprintPlotWidget")
        self.horizontalLayout_2.addWidget(self.fprintPlotWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from gui.widgets.ChromPlotWidget import ChromPlotWidget
from gui.widgets.FPrintWidget import FPrintWidget
