# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormulaFinderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(432, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tableInput = FormulaFinderInputTable(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableInput.sizePolicy().hasHeightForWidth())
        self.tableInput.setSizePolicy(sizePolicy)
        self.tableInput.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableInput.setObjectName("tableInput")
        self.verticalLayout_2.addWidget(self.tableInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddSignal = QtWidgets.QPushButton(self.tab)
        self.btnAddSignal.setObjectName("btnAddSignal")
        self.horizontalLayout.addWidget(self.btnAddSignal)
        self.btnRemoveSignal = QtWidgets.QPushButton(self.tab)
        self.btnRemoveSignal.setObjectName("btnRemoveSignal")
        self.horizontalLayout.addWidget(self.btnRemoveSignal)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnClearSignals = QtWidgets.QPushButton(self.tab)
        self.btnClearSignals.setObjectName("btnClearSignals")
        self.horizontalLayout.addWidget(self.btnClearSignals)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.btnSearch = QtWidgets.QPushButton(self.tab)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout_2.addWidget(self.btnSearch)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.treeView = QtWidgets.QTreeView(self.tab)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.verticalLayout_2.setStretch(5, 10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.treeView)
        Form.setTabOrder(self.treeView, self.btnAddSignal)
        Form.setTabOrder(self.btnAddSignal, self.btnRemoveSignal)
        Form.setTabOrder(self.btnRemoveSignal, self.btnClearSignals)
        Form.setTabOrder(self.btnClearSignals, self.btnSearch)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Query:"))
        self.btnAddSignal.setText(_translate("Form", "&Add"))
        self.btnRemoveSignal.setText(_translate("Form", "&Remove"))
        self.btnClearSignals.setText(_translate("Form", "&Clear"))
        self.btnSearch.setText(_translate("Form", "&Find MF Candidates"))
        self.label_2.setText(_translate("Form", "Candidate Molecular Formulae:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "&Search MFs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "&Parameters"))
from gui.dialogues.formula_finder.tables import FormulaFinderInputTable
